[package]
name = "spl-token-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18.0"
borsh = "0.10"
borsh-derive = "0.10"
thiserror = "1.0.0"

[features]
no-entrypoint = []